[colors.primary]
background = '#091614'
foreground = '#d7e6e2'

[colors.selection]
text = '#d7e6e2'
background = '#00504a'

[colors.cursor]
text = '#091614'
cursor = '#00decf'

[colors.normal]
black   = '#091614'
red     = '#ff5900'
green   = '#00de10'
yellow  = '#ffeb00'
blue    = '#00d2c4'
magenta = '#00665f'
cyan    = '#00decf'
white   = '#cde9e7'

[colors.bright]
black   = '#7a908e'
red     = '#ff833f'
green   = '#4cff59'
yellow  = '#fff14c'
blue    = '#24f4e6'
magenta = '#4cfff2'
cyan    = '#8cfff7'
white   = '#f2fffe'
