[colors.primary]
background = '#1a110e'
foreground = '#f1dfd9'

[colors.selection]
text = '#f1dfd9'
background = '#71361b'

[colors.cursor]
text = '#1a110e'
cursor = '#ffb597'

[colors.normal]
black   = '#1a110e'
red     = '#e14982'
green   = '#99d66e'
yellow  = '#dbab7b'
blue    = '#be6e4b'
magenta = '#bf9280'
cyan    = '#ffb597'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f92'
green   = '#abe086'
yellow  = '#e8c097'
blue    = '#ffc2a1'
magenta = '#b76155'
cyan    = '#9a6f51'
white   = '#ffffff'
