# TokyoNight Alacritty Colors
# Default colors
#  wallpaper:  The full path to the current wallpaper.
#  backend:    Current **backend** being used.
#  colorspace: Current **colorspace** being used.
#  filter:     Current **filter** being used.
#  alpha:      Default to 100, can be modified in the config file or with `--alpha`/`-a`.
#  alpha_dec:  Instead of [0..=100], displays it from 0.00 to 1.00.
#  var:        Output the color in `.
#  var.rgb:    Output the color in `rgb`.
#  var.rgba:   Output the color in `rgba`.
#  var.xrgba:  Output the color in `xrgb`.
#  var.strip:  Output the color in ` (without a `#`).
#  var.red:    Output the red value.
#  var.green:  Output the green value.
#  var.blue:   Output the blue value.
# Where `var` can be colors from `color0` to `color15`, `background`, `foreground` and `cursor`.
[colors.primary]
background = '#000000'
foreground = '{foreground}'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.bright]
black = '{color0}'	
red = '{color1}'
green = '{color2}'
yellow = '{color3}'
blue = '{color4}'
magenta = '{color5}'
cyan = '{color6}'
white = '{color7}'

# Bright colors
[colors.normal]
black = '{color8}'
red = '{color9}'
green = '{color10}'
yellow = '{color11}'
blue = '{color12}'
magenta = '{color13}'
cyan = '{color14}'
white = '{color15}'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
