# base quality (vo=gpu for gpu-hq profile's ewa_lanczos options)
vo=gpu
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
deband=yes

# keep ytdl from picking trash formats
ytdl-format=bv*[height<=?1440][vcodec!=vp9.2]+ba/b
