[colors]
background = '#121318'
foreground = '#e3e2e9'

cursor_bg = '#b2c5ff'
cursor_fg = '#121318'
cursor_border = '#b2c5ff'

selection_bg = '#314578'
selection_fg = '#e3e2e9'

ansi = ['#121318', '#ff7298', '#7fff93', '#fff872', '#9ab0f2', '#344476', '#b2c5ff', '#eff3ff']
brights = ['#999ca5', '#ff9fb9', '#a5ffb3', '#fffba5', '#bdcdff', '#c9d6ff', '#dce4ff', '#f8faff']
