[colors]
background = '#17130b'
foreground = '#eae1d4'

cursor_bg = '#e6c26c'
cursor_fg = '#17130b'
cursor_border = '#e6c26c'

selection_bg = '#5a4400'
selection_fg = '#eae1d4'

ansi = ['#17130b', '#ff766a', '#7de66b', '#ffe66a', '#dab14f', '#6a4b02', '#e6c26c', '#f1ece2']
brights = ['#959189', '#ffa299', '#aeffa0', '#ffefa0', '#fddb8a', '#ffe3a0', '#ffedc2', '#fffcf8']
