
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Inserts a blank line between shell prompts
add_newline = false
# ~/.config/starship.toml


format = '''[\[](red)[$username](yellow)[  ](green)[$hostname](blue)[\]](red) $directory $all$character'''

[hostname]
ssh_only = false
format = '$hostname'
# detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
# disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user](yellow)'
disabled = false
show_always = true
# aliases = { "corpuser034g" = "matchai" }

# ~/.config/starship.toml

# ~/.config/starship.toml

[directory]
truncation_length = 8
disabled = false
