import = [ "~/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "2.0"

[window]
opacity = 0.77
[font]
size = 20.0
[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

 
