# TokyoNight Alacritty Colors
# Default colors
#  wallpaper:  The full path to the current wallpaper.
#  backend:    Current **backend** being used.
#  colorspace: Current **colorspace** being used.
#  filter:     Current **filter** being used.
#  alpha:      Default to 100, can be modified in the config file or with `--alpha`/`-a`.
#  alpha_dec:  Instead of [0..=100], displays it from 0.00 to 1.00.
#  var:        Output the color in `.
#  var.rgb:    Output the color in `rgb`.
#  var.rgba:   Output the color in `rgba`.
#  var.xrgba:  Output the color in `xrgb`.
#  var.strip:  Output the color in ` (without a `#`).
#  var.red:    Output the red value.
#  var.green:  Output the green value.
#  var.blue:   Output the blue value.
# Where `var` can be colors from `color0` to `color15`, `background`, `foreground` and `cursor`.
[colors.primary]
background = '#000000'
foreground = '#A5A5B1'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.bright]
black = '#041B23'	
red = '#191966'
green = '#1C1B6E'
yellow = '#661953'
blue = '#621A6A'
magenta = '#231E7A'
cyan = '#6E1B50'
white = '#777788'

# Bright colors
[colors.normal]
black = '#53535F'
red = '#1C1B6E'
green = '#1E1D76'
yellow = '#6A1A5E'
blue = '#651B6E'
magenta = '#252187'
cyan = '#721C53'
white = '#777788'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
